// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Lazily-resolved reference used by the realtime accessToken callback below.
// The variable is assigned before the callback is ever invoked.
let _client: ReturnType<typeof createClient<Database>>;

_client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  // Provide the user's real JWT to the Realtime WebSocket.
  // The VITE_SUPABASE_PUBLISHABLE_KEY is not a JWT so the WebSocket
  // would otherwise fail to authenticate with Supabase Realtime.
  realtime: {
    accessToken: async () => {
      const { data: { session } } = await _client.auth.getSession();
      return session?.access_token ?? null;
    },
  },
});

export const supabase = _client;